name: Build Wheels and Test

on:
    workflow_dispatch:
    push:
        tags:
            - "v*" # Only trigger PyPI upload on version tags

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11 # cibuildwheel will handle all versions

            - name: Install cibuildwheel
              run: pip install cibuildwheel==2.18 scikit-build-core setuptools wheel twine

            - name: Build wheels
              uses: pypa/cibuildwheel@v2.18
              with:
                  package-dir: .
                  output-dir: wheelhouse
              env:
                  CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
                  # CIBW_CMAKE_OPTIONS: "-DENABLE_TESTING=ON"

            - name: Artifact wheels
              uses: actions/upload-artifact@v4
              with:
                  name: wheels-${{ matrix.os }}
                  path: wheelhouse/*.whl

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
          # Download all OS artifacts into separate subfolders
          - uses: actions/download-artifact@v4
            with:
                name: wheels-ubuntu-latest
                path: wheelhouse/ubuntu

          - uses: actions/download-artifact@v4
            with:
                name: wheels-macos-latest
                path: wheelhouse/macos

          - uses: actions/download-artifact@v4
            with:
                name: wheels-windows-latest
                path: wheelhouse/windows

          # Gather all wheels into a single folder for PyPI upload
          - name: Gather all wheels
            run: |
              mkdir -p wheelhouse/all
              cp wheelhouse/ubuntu/*.whl wheelhouse/all/
              cp wheelhouse/macos/*.whl wheelhouse/all/
              cp wheelhouse/windows/*.whl wheelhouse/all/

          # Publish all wheels to PyPI
          - name: Publish to PyPI
            uses: pypa/gh-action-pypi-publish@v1.8.8
            with:
                password: ${{ secrets.PYPI_API_TOKEN }}
                packages_dir: wheelhouse/all
